### ISSUE TITLE
Replace equal signs by {{=}} and pipes by {{!}}

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#10]
Within templates, "=" is reserved for assigning values to template parameters. For other uses, it has to be escaped by wrapping in curly brackets.

Similarly, pipe characters in the description text have to be replace by {{!}}.

**Comment by erlehmann** [comment]
Fixed by 549be59e310ca373dacc3fda9fe3e0adb4f3ed31.
