### ISSUE TITLE
Updated OAMI upload stats for JATS-Con paper

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#100]
Would be nice to have an updated version of
https://commons.wikimedia.org/wiki/File:Uploads_by_the_Open_Access_Media_Importer_to_Wikimedia_Commons_between_July_2012_and_January_2013.png .

Perhaps drop the "Timeline of ..." title and put that into the text description instead.

Pinging https://github.com/erlehmann/open-access-media-importer/issues/97

**Comment by erlehmann** [comment]
Rendering …

**Comment by erlehmann** [comment]
Rendering done: http://daten.dieweltistgarnichtso.net/pics/graphs/open-access-media-importer/plot-uploads.png
If the caption is unwanted, just crop the image?

**Comment by Daniel-Mietchen** [comment]
Thanks - that works, though there have been a few dozen more files uploaded over the course of the evening, which makes the figure for Sep 15 slightly incorrect.
