### ISSUE TITLE
PMC IDs listing underreports randomly.

### ISSUE THREAD

**Issue by erlehmann** [wpoa/open-access-media-importer#103]
<pre>
erlehmann@files:~/open-access-media-importer$ ./oa-pmc-ids --from 2013-03-01 --until 2013-09-01 | wc -w
37000
erlehmann@files:~/open-access-media-importer$ ./oa-pmc-ids --from 2013-03-01 --until 2013-09-01 | wc -w
3000
</pre>

**Comment by Daniel-Mietchen** [comment]
Any idea what kind of problem might be the cause for this?

**Comment by erlehmann** [comment]
I should probably check for the return status code.

**Comment by erlehmann** [comment]
As of 6ff21034cce3820d341f1dab2c76a4c739803c4c, oa-pmc-ids will crash if any HTTP request fails. I chose crashing instead of retrying because I do not know when and how the problem occurs.

**Comment by erlehmann** [comment]
As of d047ebb1d4c0c76f5f93aa886f58ca3a415ac1c0, oa-pmc-ids contains a verbosity option and outputs a dot to stderr for each successful HTTP request.

**Comment by erlehmann** [comment]
<pre>
% ./oa-pmc-ids --help                  
usage: oa-pmc-ids [-h] [--from FROM] [--until UNTIL] [--verbose]
List PMC IDs for articles in the PubMed Central Open Access subset.
optional arguments:
  -h, --help     show this help message and exit
  --from FROM    Only list articles updated on or after the specified date
                 (YYYY-MM-DD).
  --until UNTIL  Only list articles updated before the specified date (YYYY-
                 MM-DD).
  --verbose      Output a dot to stderr for each successful HTTP request.
Caveat: All dates are given in local time in Bethesda, Maryland: either EST
(-05:00) or EDT (-04:00), depending on the time of year.
</pre>

<pre>
% ./oa-pmc-ids --from 2013-03-01 --until 2013-03-08 | wc -w          
5649
</pre>

<pre>
% ./oa-pmc-ids --from 2013-03-01 --until 2013-03-08 --verbose | wc -w
......5649
</pre>

**Comment by erlehmann** [comment]
Closing this, as the program should crash instead of underreport due to the added assertions.
