### ISSUE TITLE
Change extension of uploaded files to ogg

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#104]
...or otherwise make sure audio files do not end up as .ogv, as per http://commons.wikimedia.org/w/index.php?title=User_talk:Open_Access_Media_Importer_Bot&diff=next&oldid=99714342 .

**Comment by erlehmann** [comment]
Probably fixed as of 247e2064391758b6ff204b5fba5ba8e8fcdd9b73.

**Comment by Daniel-Mietchen** [comment]
Cool, thanks - seems that was was the quickest fix so far!

**Comment by erlehmann** [comment]
Yeah, but note that the code is not particularly sustainable – if the OAMI does WebM encoding at some point in the future, this naming routine will break (but the previous one would have broken then as well).
