### ISSUE TITLE
Video file appears as audio

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#109]
Every once in a while, a file gets uploaded that is a video but recognized by Wikimedia Commons as an audio file, which then does not play properly. 
The latest example for that is 
https://commons.wikimedia.org/wiki/File:Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv , 
taken from 
http://dx.doi.org/10.1371/journal.pone.0072805.s001 .
It is better not to upload such files than to upload them in this corrupted state. Can we detect such corruption on our end?
The file above played OK in VLC but triggered the following error message from Movie Player: "Python (v2.7) requires to install plugins to play media files of the following type: video/x-gst-fourcc-mp2v decoder".

**Comment by erlehmann** [comment]
File on Wikimedia Commons confirmed for audio:

<pre>
% file Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv
Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv: Ogg data, Vorbis audio, mono, 48000 Hz, ~80000 bps, created by: Xiph.Org libVorbis I
</pre>

<pre>
% ogginfo Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv
Processing file "Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv"...
New logical stream (#1, serial: 2fa08d36): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20101101 (Schaufenugget)
Channels: 1
Rate: 48000
Nominal bitrate: 80,000000 kb/s
Upper bitrate not set
Lower bitrate not set
Vorbis stream 1:
    Total data length: 97051 bytes
    Playback length: 0m:12.516s
    Average bitrate: 62,033237 kb/s
Logical stream 1 ended
</pre>

<pre>
% oggz-info Intraspecific-Combinations-of-Flower-and-Leaf-Volatiles-Act-Together-in-Attracting-Hawkmoth-pone.0072805.s001.ogv
Content-Duration: 00:00:12.516
Vorbis: serialno 0799051062
    606 packets in 27 pages, 22.4 packets/page, 1.342% Ogg overhead
    Audio-Samplerate: 48000 Hz
    Audio-Channels: 1
</pre>

**Comment by erlehmann** [comment]
I'll escalate this to GStreamer developers.

**Comment by erlehmann** [comment]
Reported to GStreamer developers: https://bugzilla.gnome.org/show_bug.cgi?id=709270

**Comment by erlehmann** [comment]
GStreamer bug was marked RESOLVED FIXED in https://bugzilla.gnome.org/show_bug.cgi?id=709270#c1
