### ISSUE TITLE
Add year to cite journal template

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#11]
Example at https://commons.wikimedia.org/w/index.php?title=File%3A3D-Echo-systematically-underestimates-right-ventricular-volumes-compared-to-cardiovascular-magnetic-1532-429X-13-78-S1.ogv&diff=80589998&oldid=80539167 .

**Comment by erlehmann** [comment]
Should I distinguish between ppub and epub in a meaningful way? Also, what about the season? Two examples:

<pre>&lt;pub-date pub-type="ppub">&lt;season>Apr-Jun&lt;/season>&lt;year>2004&lt;/year>&lt;/pub-date></pre>

would become year 2004, month None, day None.

<pre>&lt;pub-date pub-type="epub">&lt;day>29&lt;/day>&lt;month>1&lt;/month>&lt;year>2008&lt;/year>&lt;/pub-date></pre>

would become year 2008, month 1, day 29.

Is that correct?

**Comment by Daniel-Mietchen** [comment]
Take whatever comes first and don't worry too much about months and days.

**Comment by erlehmann** [comment]
Fixed by 05dfd759dd93ca7ec1331fd9179fd3181598fce7.
