### ISSUE TITLE
Invalid Ogg file: Stream Undecodable

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#122]
https://commons.wikimedia.org/wiki/File:Highly-Sensitive-Quantitative-Imaging-for-Monitoring-Single-Cancer-Cell-Growth-Kinetics-and-Drug-pone.0089000.s004.ogv 
i.e.
Movie S2 from Mir M, Bergamaschi A, Katzenellenbogen B, Popescu G (2014). "Highly Sensitive Quantitative Imaging for Monitoring Single Cancer Cell Growth Kinetics and Drug Response". PLOS ONE. DOI:10.1371/journal.pone.0089000. PMID 24558461. PMC: 3928317.

**Comment by erlehmann** [comment]
Plays in mplayer, totem, VLC.

**Comment by erlehmann** [comment]
<pre>
; oggz-info Highly-Sensitive-Quantitative-Imaging-for-Monitoring-Single-Cancer-Cell-Growth-Kinetics-and-Drug-pone.0089000.s004.ogv 
Content-Duration: 00:00:26.892
Theora: serialno 0240727619
    808 packets in 204 pages, 4.0 packets/page, 0.599% Ogg overhead
    Theora-Version: 3.2.1
    Video-Framerate: 29.970 fps
    Video-Width: 640
    Video-Height: 480
Vorbis: serialno 2063825012
    1265 packets in 107 pages, 11.8 packets/page, 5.748% Ogg overhead
    Audio-Samplerate: 48000 Hz
    Audio-Channels: 2
</pre>

**Comment by erlehmann** [comment]
Firefox plays it too.

**Comment by erlehmann** [comment]
Seems like the error is on Mediawiki side: https://encrypted.google.com/search?q=%22%28Invalid+Ogg+file%3A+Stream+Undecodable%29%22&btnG=Search&oe=utf-8

**Comment by Daniel-Mietchen** [comment]
Filed as https://bugzilla.wikimedia.org/show_bug.cgi?id=61900 .

**Comment by Daniel-Mietchen** [comment]
Some more examples just in case we need them for reference:
https://commons.wikimedia.org/wiki/File:Neural-decoding-of-expressive-human-movement-from-scalp-electroencephalography-%28EEG%29-Movie1.ogv
https://commons.wikimedia.org/wiki/File:Neural-decoding-of-expressive-human-movement-from-scalp-electroencephalography-%28EEG%29-Movie2.ogv
https://commons.wikimedia.org/wiki/File:Neural-decoding-of-expressive-human-movement-from-scalp-electroencephalography-%28EEG%29-Movie3.ogv

**Comment by Daniel-Mietchen** [comment]
One more example:
https://commons.wikimedia.org/w/index.php?title=File:Helicobacter-hepaticus-Induces-an-Inflammatory-Response-in-Primary-Human-Hepatocytes-pone.0099713.s001.ogv&oldid=127083267

**Comment by Daniel-Mietchen** [comment]
One more:
https://commons.wikimedia.org/w/index.php?title=File:Single-molecule-theory-and-experiments-an-introduction-1477-3155-11-S1-S1-S1.ogv&oldid=127200269
