### ISSUE TITLE
Side issue: Getting DOI from PMCID lookup

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#125]
There is currently an effort underway to crowdsource data on articles that the Wellcome Trust have paid Article Processing Fees for - see 
https://lists.okfn.org/pipermail/open-access/2014-March/001675.html
and the spreadsheet linked therein.
It would be nice to facilitate that by automating the lookup of article DOI (column C) based on the PMCID (column B), ideally by checking for any mismatches with journal title (column H), article title (J) or licensing (M).

**Comment by Klortho** [comment]
I can do this -- I tried to get started just now, and am having a little trouble with my Perl installation.  I will look at it tomorrow morning.

**Comment by Klortho** [comment]
I got all the PMCIDs that don't have DOIs converter, [here](https://gist.github.com/Klortho/9725815).  I will try to figure out how to communicate this to the group, and/or get them merged into the document

**Comment by Klortho** [comment]
I don't know whom to contact about this.  I tried opening a chat on the google doc, but got no responses.  I think the easiest thing would be for me to create a separate, updated google doc which is a copy of the existing one, but with the new data, and then copy-paste the doi column.  Google spreadsheets has an API, but it looks very complicated.

**Comment by Daniel-Mietchen** [comment]
I'd go for copypasting from another GDoc too.

**Comment by Klortho** [comment]
I just did that.  I also resolved DOI -> PMCID, whenever that was possible.
You should close this one (I guess I don't have permission).

**Comment by Daniel-Mietchen** [comment]
Cool, thanks! Is your code available somewhere, in case we need to rerun?

**Comment by Klortho** [comment]
https://gist.github.com/Klortho/4e713dbd68f4be546c5b
To run it, first download the original as a CSV, and save it as wellcome.csv.
It generates a two-row CSV file, which I then import into a Google spreadsheet, and then copy-paste just those two rows on top of the two rows in the original.

**Comment by Daniel-Mietchen** [comment]
Thanks!
