### ISSUE TITLE
http://www.pubmedcentral.nih.gov/utils/oa/oa.fcgi is unreliable

### ISSUE THREAD

**Issue by erlehmann** [wpoa/open-access-media-importer#126]
Every dot is a successful request, every dash is a request that timeouted after 3 seconds. For the retrieval logic, check https://github.com/erlehmann/open-access-media-importer/commit/f1b2969d0970fb27f5eb2d5862d94b5509da8f32.

<pre>
; ./oa-pmc-ids --verbose --from 2014-01-01 --until 2014-01-31 | wc -w
--...--.-.-.-.-...-.---..-.----.-..---...----.--.-.--....--.----.-.-...-..-.35872
</pre>

**Comment by erlehmann** [comment]
More than half of the HTTP requests timeouted in the test case:

<pre>
In [1]: a = '--...--.-.-.-.-...-.---..-.----.-..---...----.--.-.--....--.----.-.-...-..-.'
In [2]: a.count('-')
Out[2]: 40
In [3]: a.count('.')
Out[3]: 36
</pre>

**Comment by Klortho** [comment]
That's not good.  I'll see if can be looked into.  In general, you can send these kinds of problem reports to the help desk,  pubmedcentral@ncbi.nlm.nih.gov.

Questions:  is each request for a single article, or for a batch?  Did you try a longer timeout, and if so, does it change the results?

**Comment by erlehmann** [comment]
Each request is for a batch of PMCIDs. As far as I can remember, a longer timeout only results in having to wait longer until the request fails. Before I set an explicit timeout, I sometimes got a Bad Gateway error.

**Comment by erlehmann** [comment]
For the whole application logic, see https://github.com/erlehmann/open-access-media-importer/blob/master/oa-pmc-ids.

**Comment by Klortho** [comment]
We just fixed a problem ([here](https://github.com/Klortho/JATS-to-Mediawiki/issues/1)) that was resulting in Bad Gateway errors.  But, we do think you need longer than three-second timeouts, depending on the size of the results you are expecting.  We can't find any errors in our logging system that might correspond to your tests, so there is not much we can do.

I'll close this for now, but if you encounter more errors, please let us know the details:  What were the specific requests, what date/time did you make it, etc.

**Comment by erlehmann** [comment]
Chris Maloney notifications@github.com writes:

> We just fixed a problem
> ([here](https://github.com/Klortho/JATS-to-Mediawiki/issues/1)) that
> was resulting in Bad Gateway errors.  But, we do think you need longer
> than three-second timeouts, depending on the size of the results you
> are expecting.

So what would be normal (95th percentile served) response times?

## 

Nils Dagsson Moskopp // erlehmann
http://dieweltistgarnichtso.net

**Comment by Klortho** [comment]
I'm not aware that we've done that kind of analysis, and as I mentioned, it would depend on the size of the response.

**Comment by erlehmann** [comment]
How can I test?
