### ISSUE TITLE
Transfer OAMI to WPOA organization

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#133]
We have created a GitHub organization for code related to WikiProject Open Access:
https://github.com/wpoa , as discussed in 
https://github.com/Daniel-Mietchen/OA-signalling/issues/79
and
https://github.com/Daniel-Mietchen/OA-signalling/issues/80 .

The OAMI would be a good fit for that, so I think it would be good to transfer this repository to that organization, as per 
https://help.github.com/articles/how-to-transfer-a-repository .
It seems I don't have the rights to do this, but @erlehmann has.

**Comment by RaphaelWimmer** [comment]
I agree.

**Comment by erlehmann** [comment]
Reading the transfer document right now.

**Comment by erlehmann** [comment]
Done reading. I have never redirected a repository, though. Let me try.

**Comment by erlehmann** [comment]
Transfer done. Everything okay?

**Comment by erlehmann** [comment]
Haha, very funny, I cannot close the issue now.

**Comment by Daniel-Mietchen** [comment]
Thanks - seems to have worked. I am new to this too and think you should have admin rights here. Closing now.
