### ISSUE TITLE
PMCID mismatch

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#135]
The file 
https://commons.wikimedia.org/wiki/File:Multiparametric-MRI-Analysis-for-the-Identification-of-High-Intensity-Focused-Ultrasound-Treated-pone.0099936.s004.ogv (which also figures in #134) has a wrong PMCID, which I manually corrected via
https://commons.wikimedia.org/w/index.php?title=File%3AMultiparametric-MRI-Analysis-for-the-Identification-of-High-Intensity-Focused-Ultrasound-Treated-pone.0099936.s004.ogv&diff=128321616&oldid=126998746 .

How is that possible?

**Comment by Daniel-Mietchen** [comment]
Another case:
https://commons.wikimedia.org/w/index.php?title=User_talk:Open_Access_Media_Importer_Bot&oldid=135391779#Wrong_PMC_ID

**Comment by erlehmann** [comment]
No Idea, but this does not happen on the wmde-review branch.
