### ISSUE TITLE
No new files uploaded for more than a week

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#139]
I have been running oami_pmc_doi_import.sh manually (the cron is defunct, as per https://github.com/wpoa/open-access-media-importer/issues/112#issuecomment-48084948 ) as usual on a roughly daily basis, but no files have been uploaded since the early morning of Nov 1, even though a number of papers with audio or video have been indexed in PMC afterwards (e.g.
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4218841/?report=classic#pone.0111060.s009 or http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4218721/?report=classic#pone.0111330.s001 ), and their DOIs have been amongst those that I have had the script work on.

Any ideas?

**Comment by erlehmann** [comment]
I replied to that via email. Seems GitHub is at the last step of embrace, extend, extinguish – the email does not show up.

**Comment by erlehmann** [comment]
I see the problem and am going to debug this. Note that I am currently
  working on the wmde-review branch which contains a full refactoring of
  some of the critical functions, so it might be that a bugfix will have
  to be delayed until that branch is fully reviewed and merged to master.

**Comment by erlehmann** [comment]
I noticed that some license-p elements are currently ignored by the PMC source module.

**Comment by Daniel-Mietchen** [comment]
It seems to work again, although I have not changed anything in the code. Closing for the moment, but I'd be interested to read what you found out on the matter - were there some changes on the PMC end?

**Comment by erlehmann** [comment]
Nope, found nothing.
