### ISSUE TITLE
replace newlines in title (was: wikitools.page.BadTitle)

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#17]
Traceback (most recent call last):
  File "./oa-put", line 135, in <module>
    wiki_file = wikitools.wikifile.File(wiki=wiki, title=wiki_filename)
  File "/home/daniel/open-access-media-importer/wikitools/wikifile.py", line 41, in **init**
    page.Page.**init**(self, wiki, title, check, followRedir, section, sectionnumber)
  File "/home/daniel/open-access-media-importer/wikitools/page.py", line 108, in **init**
    self.setPageInfo()
  File "/home/daniel/open-access-media-importer/wikitools/page.py", line 151, in setPageInfo
    raise BadTitle(self.title)
wikitools.page.BadTitle: Seasonal-and-Long-Term-Changes-in-Relative-Abundance-of-Bull-Sharks
## --------------------from-a-pone.0016597.s004.ogv

Affected DOIs:
10.1371/journal.pone.0016597
10.1371/journal.pone.0019602
10.1186/1741-7007-7-56
10.1371/journal.pone.0017721
10.1371/journal.pone.0019727

**Comment by Daniel-Mietchen** [comment]
Seems to boil down to new lines in article title.

**Comment by Daniel-Mietchen** [comment]
Some more:
10.1371/journal.pone.0020031

**Comment by Daniel-Mietchen** [comment]
One more: 
10.1371/journal.pone.0018293

**Comment by Daniel-Mietchen** [comment]
One more:
10.1371/journal.ppat.100254

**Comment by erlehmann** [comment]
Fixed by f7d88c1bf9c06647381cced5f39b961c6a45216d.

**Comment by Daniel-Mietchen** [comment]
this fix was for page title, not for article title in upload template:
http://commons.wikimedia.org/w/index.php?title=File%3ASocial-Interactions-of-Juvenile-Brown-Boobies-at-Sea-as-Observed-with-Animal-Borne-Video-Cameras-pone.0019602.s002.ogv&diff=84012195&oldid=84012073 .

25 new files from the DOIs mentioned above:
http://commons.wikimedia.org/w/index.php?title=Special:Contributions/Open_Access_Media_Importer_Bot&offset=20121201060805&limit=25&target=Open+Access+Media+Importer+Bot .

**Comment by erlehmann** [comment]
Fixed by 8f201fb29b50b93e45befa0a781a30c48ac27a5b.
