### ISSUE TITLE
Unusual MIME type check results

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#20]
Just wanted to flag 10.1371/journal.pone.0002276 as a DOI for which the MIME type check is unusually surprising:
DOI 10.1371/journal.pone.0002276, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2386968/bin/pone.0002276.s001.wav, source claimed audio/wav but is video/x-ms-asf.
DOI 10.1371/journal.pone.0002276, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2386968/bin/pone.0002276.s002.doc, source claimed application/msword but is video/x-ms-asf.                                       |

No idea what caused that.

Interestingly, the XML at PLOS seems to indicate the MIME type correctly, and it fits with the indications in the HTML.

**Comment by erlehmann** [comment]
I just downloaded them, both seems to be ASF Video with WMV 9 and WMA 8 content. Weird.

**Comment by erlehmann** [comment]
Closing this issue because I cannot do anything about it.
