### ISSUE TITLE
Removal of italics introduces line breaks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#23]
...that then have to be removed again. Better to fix that right away. Think I had filed that one already but couldn't find it right now, so opening up a new one.

Examples:
http://commons.wikimedia.org/w/index.php?title=File:With-a-Flick-of-the-Lid-A-Novel-Trapping-Mechanism-in-Nepenthes-gracilis-Pitcher-Plants-pone.0038951.s002.ogv&diff=prev&oldid=81229936

http://commons.wikimedia.org/w/index.php?title=File:With-a-Flick-of-the-Lid-A-Novel-Trapping-Mechanism-in-Nepenthes-gracilis-Pitcher-Plants-pone.0038951.s003.ogv&diff=prev&oldid=81229990

**Comment by erlehmann** [comment]
Probably fixed by d082bcfc2a3ccbcb594847c9050c481f2aecf289.
