### ISSUE TITLE
Remove special characters from article title

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#25]
Some articles have a question mark in their title. This should be removed.
Affected DOIs:
10.1186/1472-6785-8-16

**Comment by Daniel-Mietchen** [comment]
Also remove ^,`,',",!,± and newlines from article titles. The latter would probably also fix
https://github.com/erlehmann/open-access-media-importer/issues/17 .

**Comment by Daniel-Mietchen** [comment]
Perhaps it would be best to scan the existing database for characters in article titles, and once we have the complete list, we can decide which ones should go into page titles on Commons.

**Comment by erlehmann** [comment]
Is this still relevant?

**Comment by Daniel-Mietchen** [comment]
Yes, but it's getting less urgent the longer we wait. In principle, all of these are fine as MediaWiki page titles, but in practice, hickups because of such characters are not infrequent. For instance, a number of OAMI files did not render properly in thumbnail view for a few weeks, due to them having pluses in the file name.

**Comment by erlehmann** [comment]
Please note down the characters that are problematic here then.

**Comment by Daniel-Mietchen** [comment]
From
http://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(technical_restrictions)#Forbidden_characters :
The following characters cannot be used at all: # < > [ ] | { } _

Further problematic ones:
http://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(technical_restrictions)#Other_problematic_characters ,
especially  ʻ ʾ ʿ ᾿ ῾ ‘ ’ “ ” (except apostrophe, which is allowed).

**Comment by Daniel-Mietchen** [comment]
Case in point:
"Disruption of actin filaments induces mitochondrial Ca2+ release to the cytoplasm and [Ca2+]c changes in Arabidopsis root hairs" ( http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2923527/ ) gives a Bad Title error too.

**Comment by erlehmann** [comment]
Forbidden characters are stripped as of 319fe86c99037d1d31a6e3bf7206cbb49d37796d.
http://commons.wikimedia.org/wiki/File:Disruption-of-actin-filaments-induces-mitochondrial-Ca2%2B-release-to-the-cytoplasm-and-Ca2%2Bc-changes-1471-2229-10-53-S1.ogv

Should the “further problematic characters” just be dropped like the forbidden ones?

**Comment by erlehmann** [comment]
Oh, well … since the title of this issue is “Remove special characters from article title”, I just fixed it: 88752fa8ca6846dbaf341ae5acf752dbd280dc8e.
