### ISSUE TITLE
Indicate completion of conversion and beginning of upload

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#28]
Since the converter stalls so often, it would be good to see the completion of the conversion marked by a statement like "conversion done" for each individual file. This seems to in terms of the progress bar, but it typically shows 96% or so after the last conversion, rather independent of whether the upload (which sometimes may take time as well) is in progress or not.

Similarly, it would be good to indicate when the upload process starts.

**Comment by erlehmann** [comment]
Fixed by ee0c32f509526b0ebe6e1a8beb56c5bc7000b40b.
