### ISSUE TITLE
Remove "Additional file #number" from BMC descriptions

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#29]
Remove the whole first line if it reads as such in BMC file descriptions, as per
http://commons.wikimedia.org/w/index.php?title=Commons%3ABots%2FRequests%2FOpen_Access_Media_Importer_Bot&diff=81305989&oldid=81281322 .

BMC journals can be identified via the DOI prefix 10.1186.

**Comment by erlehmann** [comment]
Fixed in a journal-agnostic way by bd8f814b042ca11f0d266befbe888b35bc846ea5.
