### ISSUE TITLE
Additional categories "Sound" and "Videos"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#31]
For sound files, please always add 
[[Category:Sound]]
and for videos (with or without sound),
[[Category:Videos]].

**Comment by Daniel-Mietchen** [comment]
Should perhaps go into line 78 of
https://github.com/erlehmann/open-access-media-importer/blob/bd8f814b042ca11f0d266befbe888b35bc846ea5/helpers/template.py :
instead of
text += "[[Category:Media from %s]]\n" % _escape(journal_title) ,
put 

text += "[[Category:Videos from %s]]\n" % _escape(journal_title)
or

text += "[[Category:Sounds from %s]]\n" % _escape(journal_title)

**Comment by Daniel-Mietchen** [comment]
For the time being, perhaps
[[Category:Videos from open-access scholarly articles]]
and

[[Category:Audio files from open-access scholarly articles]]
would be best.

**Comment by erlehmann** [comment]
Fixed as of 6b701c55d4f2a30594c9a47c86c36128e955ac50.
