### ISSUE TITLE
Bot approved - change edit summary

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#32]
Change line 141 in
https://github.com/erlehmann/open-access-media-importer/blob/1e73fa16b40de1b030627ea5ab1fc77f4729a2e6/oa-put

from
comment = 'Uploaded with the Open Access Media Importer. (test edit) [[Commons:Bots/Requests#Open_Access_Media_Importer_Bot_.28talk.C2.A0.C2.B7_contribs.29|botrequest]]'

to
comment = 'Automatically uploaded media file from [[:en:Open access|Open Access]] source. Please report problems or suggestions [[User talk:Open Access Media Importer Bot|here]].'

**Comment by erlehmann** [comment]
Fixed with c678507112e44b1ac5771173dc7c4f34d6bdc8b4.
