### ISSUE TITLE
Capital letters in category names

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#34]
If more than one letter in a word belonging to a category name is a capital letter, then capital letters in that word should remain as they are. Examples: DNA; HeLa cells.

**Comment by Daniel-Mietchen** [comment]
Some category names with wrong  capitalization (from http://commons.wikimedia.org/wiki/Category:Uploaded_with_Open_Access_Media_Importer_and_needing_category_review ):

[×] 3t3 cells‎ (13 F)
[×] Cd8-positive t-lymphocytes‎ (14 F)
[×] Cyclic amp‎ (10 F)
[×] Dna primers‎ (32 F)
[×] Dna repair‎ (7 F)
[×] Fungal dna‎ (9 F)
[×] Gtp-binding protein alpha subunits‎ (9 F)
[×] Gtpase signaling (7 F)
[×] Hela cells‎ (73 F)
[×] Messenger rna‎ (41 F)
[×] Nadph oxidase‎ (20 F)
[×] Nih 3t3 cells‎ (25 F)
[×] Rac1 gtp-binding protein‎ (15 F)
[×] Rna interference‎ (60 F)
[×] Small interfering rna‎ (40 F)
[×] Topoisomerase ii inhibitors‎ (12 F)
[×] Type ii dna topoisomerases‎ (16 F)
[×] Vascular endothelial growth factor a‎ (9 F)
[×] Wiskott-aldrich syndrome protein family‎ (21 F)

**Comment by erlehmann** [comment]
Fixed with 7eaa296e06cab76498f605b6ed35a52c5a66a95d.

**Comment by Daniel-Mietchen** [comment]
I just ran this new version over a few articles, and it seems that hyphenated items would better have to be treated as different words: if the first word is hyphenated, then the second part (or any further ones) should only be capitalized if they contain more than one capital letter:

Plant-Environment Interactions ==> Plant-environment interactions 
Rac1 GTP-Binding Protein ==> Rac1 GTP-binding protein

**Comment by erlehmann** [comment]
Partially fixed with a3fa63cbec6f9262121e89271c18cbd0804a1ef8 and 8bcef5d8a34406b8481bfc9818a8fbab2b0cb060.

**Comment by Daniel-Mietchen** [comment]
http://commons.wikimedia.org/wiki/File:Neurons-are-MHC-Class-I-Dependent-Targets-for-CD8-T-Cells-upon-Neurotropic-Viral-Infection-ppat.1002393.s007.ogv
had "Rna viruses",
while
http://commons.wikimedia.org/wiki/File:Neurons-are-MHC-Class-I-Dependent-Targets-for-CD8-T-Cells-upon-Neurotropic-Viral-Infection-ppat.1002393.s011.ogv
had "RNA viruses" (see version history).

Are some of the descriptions cached from earlier runs?

**Comment by Daniel-Mietchen** [comment]
http://commons.wikimedia.org/wiki/File:The-Functions-of-Myosin-II-and-Myosin-V-Homologs-in-Tip-Growth-and-Septation-in-Aspergillus-nidulans-pone.0031218.s009.ogv
had both 
"Myosin type V"
and
"Myosin type ii" (which should be "Myosin type II").

**Comment by Daniel-Mietchen** [comment]
http://commons.wikimedia.org/wiki/File:Dtorsin-the-Drosophila-Ortholog-of-the-Early-Onset-Dystonia-TOR1A-(DYT1)-Plays-a-Novel-Role-in-pone.0026183.s006.ogv
started out with several single-word categories: Aging, Brain, Dopamine, Larva, Mutation, Neurons, Pigmentation

**Comment by Daniel-Mietchen** [comment]
Closing - remaining issues taken over by https://github.com/erlehmann/open-access-media-importer/issues/39 .
