### ISSUE TITLE
Categories missing

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#36]
When I ran the bot tonight, it did not add subject categories to any of the files:
http://commons.wikimedia.org/w/index.php?title=Special:Contributions/Open_Access_Media_Importer_Bot&offset=20121109224355&limit=64&target=Open+Access+Media+Importer+Bot .

**Comment by erlehmann** [comment]
Probably fixed by 9c06666a003b0a8ff8d3fb5bfe541bbe38d23f4e.
