### ISSUE TITLE
Some single-word categories still slip through

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#39]
Example:
10.1371/journal.pone.0047911 (Dynamics)

http://commons.wikimedia.org/w/index.php?title=File:Switching-Dynamics-in-an-Interpersonal-Competition-Brings-about-%E2%80%9CDeadlock%E2%80%9D-Synchronization-of-pone.0047911.s010.ogv&oldid=82886583

**Comment by Daniel-Mietchen** [comment]
See also https://github.com/erlehmann/open-access-media-importer/issues/34#issuecomment-10493051

**Comment by erlehmann** [comment]
This category is actually named “Dynamics (Mechanics)”, but we remove the stuff in brackets when postprocessing category names. Therefore the length check is invalidated.

**Comment by erlehmann** [comment]
Fixed by 8f02c5a3f9fc8332d2a4c104edb5f665271f4537. See https://species-id.net/wiki/File:Switching-Dynamics-in-an-Interpersonal-Competition-Brings-about-%E2%80%9CDeadlock%E2%80%9D-Synchronization-of-pone.0047911.s010.ogv,
