### ISSUE TITLE
Frontiers licenses

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#40]
Frontiers recently switched from CC BY-NC to CC BY as their default license. However, the few files that are labeled as being CC BY normally end up recognized as "Unknown, possibly non-free license".

Examples:
10.3389/fphys.2012.00293
10.3389/fphys.2012.00414
10.3389/fmicb.2012.00338

More via https://www.google.com/search?q=10.3389+video&sugexp=chrome,mod=16&sourceid=chrome&ie=UTF-8#hl=en&tbo=d&sclient=psy-ab&q=10.3389+%22supplemental+data%22+(movie+OR+video)+%22creative+commons+attribution+license%22 .

**Comment by erlehmann** [comment]
Unfortunately, _Frontiers_ does not distinguish its licensing via use of the &lt;license> element href attribute:

<pre>
        &lt;license license-type="open-access" xlink:href="http://www.frontiersin.org/licenseagreement">
          &lt;license-p>This is an open-access article distributed under the terms of the &lt;uri xlink:type="simple" xlink:href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution License&lt;/uri>, which permits use, distribution and reproduction in other forums, provided the original authors and source are credited and subject to any copyright notices concerning any third-party graphics etc.&lt;/license-p>
        &lt;/license>
</pre>

**Comment by erlehmann** [comment]
So, should OAMI look at &lt;license-p> elements when &lt;license> elements give a proprietary license?

**Comment by Daniel-Mietchen** [comment]
probably yes.

**Comment by Daniel-Mietchen** [comment]
Frontiers articles have worked fine for a while now - closing.
