### ISSUE TITLE
Invalid Ogg file uploaded

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#41]
http://commons.wikimedia.org/wiki/File:An-Engineering-Approach-to-Extending-Lifespan-in-C.-elegans-pgen.1002780.s011.ogv (archived at 
http://www.webcitation.org/6CHU1L3U8 ).

**Comment by erlehmann** [comment]
Plays fine in mplayer, Totem, VLC until 30 seconds in.

**Comment by Daniel-Mietchen** [comment]
Any idea why it is displayed as an audio file?

**Comment by erlehmann** [comment]
<pre>
1002 ~ % file An-Engineering-Approach-to-Extending-Lifespan-in-C.-elegans-pgen.1002780.s011.ogv
An-Engineering-Approach-to-Extending-Lifespan-in-C.-elegans-pgen.1002780.s011.ogv: Ogg data, Theora video
</pre>

<pre>
1005 ~ % oggz-info An-Engineering-Approach-to-Extending-Lifespan-in-C.-elegans-pgen.1002780.s011.ogv
Content-Duration: 00:00:30.092
Theora: serialno 0114268159
    904 packets in 126 pages, 7.2 packets/page, 0.730% Ogg overhead
    Theora-Version: 3.2.1
    Video-Framerate: 29.970 fps
    Video-Width: 640
    Video-Height: 480
Vorbis: serialno 0360957546
    1415 packets in 120 pages, 11.8 packets/page, 5.642% Ogg overhead
    Audio-Samplerate: 48000 Hz
    Audio-Channels: 2
</pre>

oggz-validate shows no error.

**Comment by Daniel-Mietchen** [comment]
Similar problems have happened with about two dozen files, and they were typically fixed by uploading a WebM version. So I am assuming this has something to do with the OGG handling in MediaWiki, and close this one.
