### ISSUE TITLE
Split journal titles by colons

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#43]
Some journals have subtitles after their main title, typically separated by a colon. We should take only the part before the colon (and drop any whitespace between the final character of the journal name and the colon).

Examples:
http://commons.wikimedia.org/wiki/Category:Media_from_Evidence-based_Complementary_and_Alternative_Medicine_:_eCAM
http://commons.wikimedia.org/wiki/Category:Media_from_Algorithms_for_Molecular_Biology_:_AMB

**Comment by erlehmann** [comment]
Fixed by 82b6b49ea43578b780ab32830787f876fc791e34. See https://species-id.net/wiki/File:Shikonin-Directly-Targets-Mitochondria-and-Causes-Mitochondrial-Dysfunction-in-Cancer-Cells-726025.f2.ogv.
