### ISSUE TITLE
License check should go before MIME type check

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#51]
We only need to check freely licensed articles.

**Comment by erlehmann** [comment]
Currently working on this, refactoring the code checking for free licensing.

**Comment by Daniel-Mietchen** [comment]
Any news on this one?

**Comment by erlehmann** [comment]
Fixed as of 1d6b0a3de260b9830478d59d58a63f0778fae1fc.
