### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#55]
This one is new to me:

Removing “/home/daniel/.local/share/open-access-media-importer/pmc_pmcid.sqlite” … done.
Input PMCIDs, delimited by whitespace: Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3502255”, saving into directory “/home/daniel/.cache/open-access-media-importer/metadata/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
PLOS ONE 2012
    Improved Flow Cytometric Assessment Reveals Distinct Microvesicle (Cell-Derived Microparticle) Signatures in Joint Diseases
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
“Improved Flow Cytometric Assessment Reveals Distinct Microvesicle (Cell-Derived Microparticle) Signatures in Joint Diseases”:
    1 × application/vnd.ms-excel
    4 × image/tiff
    1 × video/x-ms-wmv

Checking MIME types …
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.#############################################                                  |
  param.append(processors[key](compiled_params[key]))
DOI 10.1371/journal.pone.0049726, http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3502255/bin/pone.0049726.s006.wmv, source claimed video/x-ms-wmv but is video/x-ms-asf.
100% |##########################################################################################################################################################################################################|
Skipping download of http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3502255/bin/pone.0049726.s006.wmv.
Skipping conversion of “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0049726.s006.wmv”, exists at “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0049726.s006.wmv.ogv”.
Traceback (most recent call last):
  File "./oa-put", line 70, in <module>
    article_pmid = efetch.get_pmid_from_doi(article_doi)
  File "/home/daniel/open-access-media-importer/helpers/efetch.py", line 29, in get_pmid_from_doi
    return tree.find('IdList/Id').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by erlehmann** [comment]
Cannot reproduce, closed.
