### ISSUE TITLE
oami_pmc_pmcid_import is too slow

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#59]
I ran oami_pmc_pmcid_import for about 24h yesterday, covering about 10k PMCIDs, which brought in new 11 files, 8 of which had to be flagged for deletion because of license mismatches between the XML and the journal website.

Considering that there are over 3.5 million articles in PMC, a rate of 10k PMCIDs per day would mean that scanning the whole database would take a year (during which a few 100k new articles would come in). So we will have to speed things up a bit. The whitelist will certainly contribute to that, but it's perhaps not the only thing we can or should do in this regard.

**Comment by erlehmann** [comment]
Skipping the MIME type check would leave us with no false positives (those would have to be detected when actually downloading the resources), but some false negatives.

**Comment by Daniel-Mietchen** [comment]
Let's first see how things go once the whitelist is operational, as per https://github.com/erlehmann/open-access-media-importer/issues/57 .

**Comment by erlehmann** [comment]
Whitelist is operational.

**Comment by Daniel-Mietchen** [comment]
Still takes months to go through the whole database, but I'm 2/3 done, so closing this one for the time being.
