### ISSUE TITLE
test case for crashing of media pipeline

### ISSUE THREAD

**Issue by erlehmann** [wpoa/open-access-media-importer#60]
I think we need a minimal script that takes a media file and tries to apply the media conversion. It could be used to help GStreamer developers reproduce our issues.

**Comment by erlehmann** [comment]
Labeled „Do it NOW“ because it would help us to fix GStreamer issues as well.

**Comment by Daniel-Mietchen** [comment]
Would be cool if that script could just be pointed to the URL of a media file, e.g.
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3011000/bin/pone.0014414.s005.avi .

**Comment by erlehmann** [comment]
We have this as of 005862326f026b9343f14e109cc6bd093a8ad778.
