### ISSUE TITLE
NameError: global name '_query' is not defined 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#65]
posting here for completeness only; was solved by rerun.

echo 3521028 | ./oami_pmc_pmcid_import 
Input PMCIDs, delimited by whitespace: Removing “/home/daniel/.cache/open-access-media-importer/metadata/raw/pmc_pmcid/efetch.fcgi0” … done.
Downloading “http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3521028”, saving into directory “/home/daniel/.cache/open-access-media-importer/metadata/raw/pmc_pmcid” …
100% |#########################################################################|
Skipping 1 records … 
PLOS ONE 2012
    Cell Origami: Self-Folding of Three-Dimensional Cell-Laden Microstructures Driven by Cell Traction Force
/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:463: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
“Cell Origami: Self-Folding of Three-Dimensional Cell-Laden Microstructures Driven by Cell Traction Force”:
    6 × video/quicktime
    6 × image/tiff

Checking MIME types …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s001.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s002.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s003.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s004.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s005.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Downloading http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3521028/bin/pone.0051085.s006.mov, saving into directory “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid” …
100% |##########################################################################################################################################################################################################|
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s001.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s001.mov.ogv” …  18% |#####################################                                                                                                                                                               done.|###############################################################################################################################################################################################           |
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s002.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s002.mov.ogv” …  22% |#############################################                                                                                                                                                       done.|#####################################################################################################################################################################                                     |
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s003.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s003.mov.ogv” …  19% |#######################################                                                                                                                                                             done.|##############################################################################################################################################################################################            |
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s004.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s004.mov.ogv” …  13% |###########################                                                                                                                                                                         done.|#################################################################################################################################################################################                         |
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s005.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s005.mov.ogv” …  18% |####################################                                                                                                                                                                done.|######################################################################################################################################################################################                    |
Converting “/home/daniel/.cache/open-access-media-importer/media/raw/pmc_pmcid/pone.0051085.s006.mov”, saving into “/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s006.mov.ogv” …   5% |###########                                                                                                                                                                                         done.|########################################################################################################################################################################################################  |
“/home/daniel/.cache/open-access-media-importer/media/refined/pmc_pmcid/pone.0051085.s001.mov.ogv” uploaded to http://commons.wikimedia.org/w/api.php.
Mediawiki API request failed, retrying.
Traceback (most recent call last):
  File "./oa-put", line 61, in <module>
    if mediawiki.is_uploaded(material):
  File "/home/daniel/open-access-media-importer/helpers/mediawiki.py", line 53, in is_uploaded
    result = query(params)
  File "/home/daniel/open-access-media-importer/helpers/mediawiki.py", line 16, in query
    return _query(request)
NameError: global name '_query' is not defined

**Comment by erlehmann** [comment]
Fixed by 78ebb4e342757acd30cea34f513e66099f9f8a6d.
