### ISSUE TITLE
No PubMed Central IDs for given DOIs found

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#66]
With respect to the example mentioned in 
https://github.com/erlehmann/open-access-media-importer/issues/65 (where oami_pmc_pmcid_import knew the DOI of the article), I noticed that running oami_pmc_doi_import produces an error:
echo 10.1371/journal.pone.0051085 | ./oami_pmc_doi_import
Input DOIs, delimited by whitespace: Getting PubMed Central IDs for given DOIs … Traceback (most recent call last):
  File "./oa-get", line 122, in <module>
    for result in source_module.download_metadata(source_path):
  File "/home/daniel/open-access-media-importer/sources/pmc_doi.py", line 56, in download_metadata
    raise RuntimeError, 'No PubMed Central IDs for given DOIs found.'
RuntimeError: No PubMed Central IDs for given DOIs found.

**Comment by erlehmann** [comment]
I cannot reproduce this.
