### ISSUE TITLE
Refactor inconsistent python-colorama use

### ISSUE THREAD

**Issue by RaphaelWimmer** [wpoa/open-access-media-importer#68]
String generation for console output in sources/pmc.py and helpers/**init**.py uses python-colorama. However, it is implemented differently in both files. 
Refactor to make code easier to maintain.

**Comment by erlehmann** [comment]
It seems I should use the logging module. http://docs.python.org/2/library/logging.html

**Comment by erlehmann** [comment]
python-colorama is no longer a dependency as of f246ce4c510ceca00b06910ed948eb1f0138ce23.
