### ISSUE TITLE
OAMI code sprint on May 24-25?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#70]
I shall be in Berlin on May 24-25 and would like to jump on the opportunity to have some of the remaining issues ironed out, so that we can really switch to routine operation.

**Comment by erlehmann** [comment]
Daniel Mietchen notifications@github.com schrieb am Sun, 12 May 2013
17:03:55 -0700:

> I shall be in Berlin on May 24-25 and would like to jump on the
> opportunity to have some of the remaining issues ironed out, so that
> we can really switch to routine operation.

Ok, scheduled.

## 

Nils Dagsson Moskopp // erlehmann
http://dieweltistgarnichtso.net

**Comment by Daniel-Mietchen** [comment]
Issues opened during the sprint:
https://github.com/erlehmann/open-access-media-importer/issues/71
https://github.com/erlehmann/open-access-media-importer/issues/72
https://github.com/erlehmann/open-access-media-importer/issues/73

Issues closed:
https://github.com/erlehmann/open-access-media-importer/issues/71
https://github.com/erlehmann/open-access-media-importer/issues/40
https://github.com/erlehmann/open-access-media-importer/issues/8
https://github.com/erlehmann/open-access-media-importer/issues/35
https://github.com/erlehmann/open-access-media-importer/issues/51

Issues commented on:
https://github.com/erlehmann/open-access-media-importer/issues/58
https://github.com/erlehmann/open-access-media-importer/issues/31
https://github.com/erlehmann/open-access-media-importer/issues/47
