### ISSUE TITLE
Install python package werkzeug

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#71]
pip install werkzeug

**Comment by RaphaelWimmer** [comment]
I have installed Debian package 'python-werkzeug'. 
(why not flask, btw?)

**Comment by erlehmann** [comment]
Because OAMI only uses the caching capabilities of werkzeug for now.

**Comment by erlehmann** [comment]
For documentation of what we are using, see here: http://werkzeug.pocoo.org/docs/contrib/cache/.
I think we may be able to use werkzeug caching at other places in the application as well.
