### ISSUE TITLE
Keep non-ASCII characters in description

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#74]
We purposefully remove non-ASCII characters from the file names on Commons, but apparently - and without any purpose apparent to me - also from the article titles or author names in the description.

Example:
http://commons.wikimedia.org/wiki/File:-Arrestin2-Regulates-Lysophosphatidic-Acid-Induced-Human-Breast-Tumor-Cell-Migration-and-Invasion-pone.0056174.s003.ogv

**Comment by erlehmann** [comment]
None of the names in the <pre>&lt;contrib-group></pre> element of this article seems to contain non-ASCII characters. Closing bug for that reason.

<pre>
      &lt;contrib-group>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Alemayehu&lt;/surname>
            &lt;given-names>Mistre&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Dragan&lt;/surname>
            &lt;given-names>Magdalena&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Pape&lt;/surname>
            &lt;given-names>Cynthia&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Siddiqui&lt;/surname>
            &lt;given-names>Iram&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff2">
            &lt;sup>2&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Sacks&lt;/surname>
            &lt;given-names>David B.&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff6">
            &lt;sup>6&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Di Guglielmo&lt;/surname>
            &lt;given-names>Gianni M.&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Babwah&lt;/surname>
            &lt;given-names>Andy V.&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
          &lt;xref ref-type="aff" rid="aff3">
            &lt;sup>3&lt;/sup>
          &lt;/xref>
          &lt;xref ref-type="aff" rid="aff4">
            &lt;sup>4&lt;/sup>
          &lt;/xref>
          &lt;xref ref-type="aff" rid="aff5">
            &lt;sup>5&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
        &lt;contrib contrib-type="author">
          &lt;name>
            &lt;surname>Bhattacharya&lt;/surname>
            &lt;given-names>Moshmi&lt;/given-names>
          &lt;/name>
          &lt;xref ref-type="aff" rid="aff1">
            &lt;sup>1&lt;/sup>
          &lt;/xref>
          &lt;xref ref-type="corresp" rid="cor1">
            &lt;sup>*&lt;/sup>
          &lt;/xref>
        &lt;/contrib>
      &lt;/contrib-group>
</pre>
