### ISSUE TITLE
Use kwd tag to create categories for Commons

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#86]
See
http://jats.nlm.nih.gov/archiving/tag-library/1.0/?elem=kwd

For 
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3698203 ,
this would be
"Postnatal retina", "in vitro electroporation", "Live 2-photon microscopy", "Hierarchical cluster analysis".

Not everyone uses this tag, but if it is available, it tends to be more precise (and thus more useful) in terms of categories for Commons.

**Comment by Daniel-Mietchen** [comment]
Some other examples:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3763220
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3771564
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3766224
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3763220

**Comment by Daniel-Mietchen** [comment]
More info via http://jats.nlm.nih.gov/archiving/tag-library/0.4/n-pu72.html .

**Comment by Daniel-Mietchen** [comment]
The essence is also in  
http://chrismaloney.org/InconsistentXml/JatsCon2013.html#keywords .

**Comment by erlehmann** [comment]
Currently, we get our categories for Wikimedia Commons from the descendents of the &lt;article-categories&gt; element. Should I add to that behaviour or replace it entirely?

**Comment by Daniel-Mietchen** [comment]
Add to it.

**Comment by erlehmann** [comment]
Fixed as of 70bdb67369e279b9ff5472f3764fd15110259c18.
