### ISSUE TITLE
Avoid empty descriptions in template.py

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#88]
add check to https://github.com/erlehmann/open-access-media-importer/blob/4c7ded40e54e89507b1acb10f7c94374c2dd2468/helpers/template.py#L48 so that empty descriptions do not get posted with the {{en|1=}} envelope, as per http://commons.wikimedia.org/w/index.php?title=User_talk:Open_Access_Media_Importer_Bot&oldid=99490463#Category:Language_templates_with_no_text_displayed .

**Comment by erlehmann** [comment]
Assertion introduced as of ceba6b697726e559dbb254d340bf01cd6bcb4786. Bug will be closed as soon as I know what should be done instead.

**Comment by Daniel-Mietchen** [comment]
just leave the description field empty then - there is a Commons category that allows to track such cases.

**Comment by Daniel-Mietchen** [comment]
What we need to change is shown at https://commons.wikimedia.org/w/index.php?title=File:Motor-tics-evoked-by-striatal-disinhibition-in-the-rat-Movie1.ogv&diff=prev&oldid=105607572 .

**Comment by erlehmann** [comment]
Hopefully fixed as of 13cd48bb82fa9a5fff6946735383a6e207c2ab3b.

**Comment by Daniel-Mietchen** [comment]
Looks good, thanks.

**Comment by Daniel-Mietchen** [comment]
Did not work for 
https://commons.wikimedia.org/wiki/File:Side-effect-of-acting-on-the-world-acquisition-of-action-outcome-statistic-relation-alters-visual-Movie3.ogv .

**Comment by erlehmann** [comment]
The XML in question is:

<pre>
      &lt;supplementary-material content-type="local-data">
        &lt;media xlink:href="Movie3.MOV">
          &lt;caption>
            &lt;p>Click here for additional data file.&lt;/p>
          &lt;/caption>
        &lt;/media>
      &lt;/supplementary-material>
</pre>

**Comment by erlehmann** [comment]
See http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=3782700

**Comment by Daniel-Mietchen** [comment]
Sure, but since we ignore statements containing "click", there should be no

```
{{en|1= }}
```

on the page, as this requires cleanup as per 
https://commons.wikimedia.org/w/index.php?title=File%3ASide-effect-of-acting-on-the-world-acquisition-of-action-outcome-statistic-relation-alters-visual-Movie3.ogv&diff=106524701&oldid=106502877 .

**Comment by erlehmann** [comment]
Let me find where the cleanup happens.

**Comment by erlehmann** [comment]
The description seems to be a single space.

**Comment by Daniel-Mietchen** [comment]
Yep. Where does that come from?

**Comment by erlehmann** [comment]
Whitespace issue should be fixed as of b91c061cceb38fceae556b950776f3a766f6da35.

**Comment by erlehmann** [comment]
I think the single space is an artifact of the cleanup process.

**Comment by Daniel-Mietchen** [comment]
Looks good, thanks. Next one is https://github.com/erlehmann/open-access-media-importer/issues/111 .
