### ISSUE TITLE
Wikimedia platforms switch to HTTPS - what does this mean for the bot?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#91]
Seen at
http://lists.wikimedia.org/pipermail/pywikipedia-l/2013-August/008190.html .

**Comment by erlehmann** [comment]
I think OAMI already uses a HTTPS URL for communication with Wikimidia Commons: https://commons.wikimedia.org/w/api.php – therefore there should be no problems.

To confirm that an OAMI deployment is using a HTTPS URL, check the file .config/open-access-media-importer/userconfig in the bot user's home directory.

**Comment by Daniel-Mietchen** [comment]
My userconfig was not yet set to https, but I fixed it now. Thanks.
