### ISSUE TITLE
Prepare slides for JATS-Con talk

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#98]
Let's collect directly OAMI-related information for the talk here, for easy inclusion in http://chrismaloney.org/notes/OAMI%20JatsCon%20slides,%202013 .

**Comment by Daniel-Mietchen** [comment]
Slides are being collected at https://en.wikipedia.org/wiki/User:Daniel_Mietchen/Talks/JATS-Con_Impromptu_2013 .

**Comment by Daniel-Mietchen** [comment]
More XML inconsistencies, observed by others: https://twitter.com/alexsdutton/status/448749970322358274 .

**Comment by alexdutton** [comment]
The XSL we used to parse the JATS XML into something easier to work with for pulling out citations is [on GitHub](https://github.com/opencitations/PubMed-OA-network-analysis-scripts/blob/master/article-data.xsl). In particular, [lines 530 f.f.](https://github.com/opencitations/PubMed-OA-network-analysis-scripts/blob/master/article-data.xsl#L530) are the bit that deals with implicit reference ranges. I should warn you that I wrote that XSL in my early days ;-)

**Comment by Klortho** [comment]
Quoting from @alexsdutton 's tweet:

> either <xref ref="#C1 #C2 #C3">1–3</xref> (good), or <xref ref="#1">1</xref>–<xref ref="#3">3</xref> (bad)

Note, `ref` should be `rid`.  Interestingly, the PMC  tagging guidelines [specify what you're calling the "bad" style](http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-xref).

We're aware there's a lot of variation in the way ranges of references are tagged in the article body, and it is a huge problem for us as well.  Not sure what can be done about it, though.

**Comment by Daniel-Mietchen** [comment]
The slides are up at 
https://en.wikipedia.org/wiki/User:Daniel_Mietchen/Talks/JATS-Con_2014/Inconsistent_XML_as_a_Barrier_to_Reuse_of_Open_Access_Content
and the video recording sits at
http://videocast.nih.gov/summary.asp?Live=13961&start=15090&bhcp=1 .
The talk was featured prominently in Jeff Beck's lightning talk on Day 2:
http://videocast.nih.gov/summary.asp?Live=13963&start=11980&bhcp=1 .
