### ISSUE TITLE
Prepare JATS-Con submission

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wpoa/open-access-media-importer#99]
Let's collect directly OAMI-related information for the paper here, for easy inclusion in http://chrismaloney.org/notes/OAMI%20JatsCon%20paper,%202013 .

**Comment by Klortho** [comment]
On the paper page, I'm putting meta-information, comments, and stuff like that in block quotes, to preserve it but separate it clearly from the actual prose of the paper.

**Comment by Daniel-Mietchen** [comment]
Submitted. Copy at http://chrismaloney.org/InconsistentXml/JatsCon2013.html .
